baseurl = "https://jakutt.pages.taltech.ee/spacevolcanoes-wiki/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Spacevolcanoes Wiki"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Say no to poverty!"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Jaak Kütt"
  email = "jakutt@ttu.ee"
  gitlab = "jakutt"

[[menu.main]]
    identifier = "retros"
    name = "Retros"
    weight = 2

[[menu.main]]
    parent = "retros"
    name = "Spawn point"
    url = "page/retro-spawn-point"
    weight = 1

[[menu.main]]
    parent = "retros"
    name = "Dumpster fire"
    url = "page/retro-dumpster-fire"
    weight = 2

[[menu.main]]
    name = "Business"
    url = "page/business-analysis"
    weight = 3

[[menu.main]]
    name = "Money"
    url = "page/money"
    weight = 3
