baseurl = "https://jakutt.pages.taltech.ee/spacevolcanoes-wiki/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Spacevolcanoes Wiki"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Say no to poverty!"
  logo = "logo.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false


[Author]
  name = "Jaak Kütt, Kristjan Kõiv, Kristajn Koitla, Mart Kaasik"

[[menu.main]]
    name = "Technical"
    url = "page/technical"
    weight = 1

[[menu.main]]
    identifier = "retros"
    name = "Retros"
    weight = 2

[[menu.main]]
    parent = "retros"
    name = "Spawn point"
    url = "page/retro-spawn-point"
    weight = 1

[[menu.main]]
    parent = "retros"
    name = "Dumpster fire"
    url = "page/retro-dumpster-fire"
    weight = 2

[[menu.main]]
    parent = "retros"
    name = "Mild food poisoning"
    url = "page/retro-mild-food-poisoning"
    weight = 3

[[menu.main]]
    parent = "retros"
    name = "Abandoned cabin"
    url = "page/retro-abandoned-cabin"
    weight = 4

[[menu.main]]
    name = "Business"
    url = "page/business-analysis"
    weight = 3

[[menu.main]]
    name = "Money"
    url = "page/money"
    weight = 3
